### ISSUE TITLE
开源项目更新是不推送到git了吗qwp

### ISSUE THREAD

**Issue by BiliRumble** [ChinaMcAlly/limboauthserver#5]
1个多月没动静了,本来想自己看看你不能搞1.19.3兼容,结果研究不透协议包awa
所以下一次更新大概在什么时候awa
抑或所有没有使用代理服务器(如Velociy)进行多版本兼容的方法awa

**Comment by cnluminous** [comment]
此项目目前正在重构，如需高版本兼容可以使用velocity，bungeecord，waterfall等proxy代理安装Viaversion进行向上兼容，最近会提交1.19.4的兼容版本

**Comment by cnluminous** [comment]
目前服务器是采用的viaversion向上兼容

**Comment by BiliRumble** [comment]
知道了,谢谢
awa
